# -*- coding: utf-8 -*-
"""AHI_DEMO.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1AoH8AsWUd-qgncoOdtYzLxTn4xdYkddr
"""

import pandas as pd 
import sqlalchemy
from sqlalchemy import create_engine
!pip install pymysql
!pip install cryptography

pip install cryptography

from google.colab import files
uploaded = files.upload()

import io
import pandas as pd
df = pd.read_csv(io.BytesIO(uploaded['H1N1_Flu_Vaccines.csv']))
MYSQL_HOSTNAME = '20.115.25.244'
MYSQL_USER = 'DBAMYSQL'
MYSQL_PASSWORD = 'ahi2021'
MYSQL_DATABASE = 'tempdata'

connection_string = f'mysql+pymysql://{MYSQL_USER}:{MYSQL_PASSWORD}@{MYSQL_HOSTNAME}:3306/{MYSQL_DATABASE}'
engine = create_engine(connection_string)

TABLENAME = 'H1N1'

print(engine.table_names)

df.to_sql(TABLENAME, con=engine)